{% set name = "tsdst" %}
{% set version = "1.0.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
    
source:
  path: ..
    
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - matplotlib>=3.1.0
    - numba>=0.44.1
    - numdifftools>=0.9.39
    - numpy>=1.16.4
    - pandas>=0.24.2
    - scikit-learn>=0.22.1
    - scipy>=1.2.1
    - seaborn>=0.11.0
    - sqlalchemy>=1.3.4
    - statsmodels>=0.9.0
  run:
    - python
    - matplotlib>=3.1.0
    - numba>=0.44.1
    - numdifftools>=0.9.39
    - numpy>=1.16.4
    - pandas>=0.24.2
    - scikit-learn>=0.22.1
    - scipy>=1.2.1
    - seaborn>=0.11.0
    - sqlalchemy>=1.3.4
    - statsmodels>=0.9.0

test:
  imports:
    - tsdst
        
about:
  home: https://tomwerner5.github.io/tsdst/
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: "A low-key data science and statistics toolkit"
  description: "See https://tomwerner5.github.io/tsdst/"
  doc_url: 'https://tomwerner5.github.io/tsdst/'
  dev_url: 'https://github.com/tomwerner5/tsdst/'
    
extra:
  recipe-maintainers: 'Tom W.'
